---
# Per environment values which override defaults in hmpps-community-payback-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: community-payback-api-test.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-community-payback-api-test-cert

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    APPLICATIONINSIGHTS_ROLE_NAME: community-payback-api-test
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SENTRY_ENVIRONMENT: test
    SPRING_PROFILES_ACTIVE: test

    COMMUNITY_PAYBACK_DOMAIN_EVENTS_ENVIRONMENT: test
    COMMUNITY_PAYBACK_DOMAIN_EVENTS_DETAILS_URL_PATTERN: https://community-payback-api-test.hmpps.service.justice.gov.uk/domain-event-details/#type/#id

    # we disable this in test because dev will be handling the same messages
    COMMUNITY_PAYBACK_EDUCATION_COURSE_INTEGRATION_ENABLED: false

    COMMUNITY_PAYBACK_AUTO_SEED_ENABLED: true

    COMMUNITY_PAYBACK_SCHEDULING_ENABLED: true

    CLIENT_COMMUNITY_PAYBACK_AND_DELIUS_URL: http://hmpps-community-payback-api-stubs
    CLIENT_ARNS_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-community-payback-nonprod
  rdsAlertsDatabases:
    cloud-platform-2e80c5ae0324b485: "community payback"
  # API pool users = 20 per pod
  # Max expected connections for 2 x pods = 40 + additional 10 (buffer for direct connections)
  rdsAlertsConnectionThreshold: 50
  sqsAlertsQueueNames:
    - "hmpps-community-payback-devs-test-hmpps_cp_domain_events_dlq"
    - "hmpps-community-payback-devs-test-hmpps_cp_domain_events_queue"
  sqsAlertsOldestThreshold: 30
  sqsAlertsTotalMessagesThreshold: 10

deploy_stubs: true
