---
# Per environment values which override defaults in hmpps-community-payback-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: community-payback-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-community-payback-api-dev-cert

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SENTRY_ENVIRONMENT: dev
    SPRING_PROFILES_ACTIVE: dev

    COMMUNITY_PAYBACK_DOMAIN_EVENTS_ENVIRONMENT: dev
    COMMUNITY_PAYBACK_DOMAIN_EVENTS_URLS_APPOINTMENT_UPDATED: https://community-payback-api-dev.hmpps.service.justice.gov.uk/domain-event-details/appointment-updated
    COMMUNITY_PAYBACK_AUTO_SEED_ENABLED: true

    COMMUNITY_PAYBACK_SCHEDULING_ENABLED: true

    CLIENT_ARNS_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    CLIENT_COMMUNITY_PAYBACK_AND_DELIUS_URL: https://community-payback-and-delius-dev.hmpps.service.justice.gov.uk


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-community-payback-nonprod
  rdsAlertsDatabases:
    cloud-platform-05aa0645d0cf9499: "community payback"
  # API pool users = 20 per pod
  # Max expected connections for 2 x pods = 40 + additional 10 (buffer for direct connections)
  rdsAlertsConnectionThreshold: 50
  sqsAlertsQueueNames:
    - "hmpps-community-payback-devs-dev-education_course_completion_events_dlq"
    - "hmpps-community-payback-devs-dev-education_course_completion_events_queue"
    - "hmpps-community-payback-devs-dev-hmpps_cp_domain_events_dlq"
    - "hmpps-community-payback-devs-dev-hmpps_cp_domain_events_queue"
  sqsAlertsOldestThreshold: 30
  sqsAlertsTotalMessagesThreshold: 10

deploy_stubs: true

