---
# Per environment values which override defaults in hmpps-community-payback-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: community-payback-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-community-payback-api-dev-cert

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SENTRY_ENVIRONMENT: dev
    SPRING_PROFILES_ACTIVE: dev

    COMMUNITY_PAYBACK_URL_TEMPLATES_DOMAIN_EVENT_DETAIL_APPOINTMENT_OUTCOME: https://community-payback-api-dev.hmpps.service.justice.gov.uk/domain-event-details/appointment-outcome
    COMMUNITY_PAYBACK_AUTO_SEED_ENABLED: true

    CLIENT_ARNS_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    CLIENT_COMMUNITY_PAYBACK_AND_DELIUS_URL: http://hmpps-community-payback-api-stubs


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-community-payback-nonprod

deploy_stubs: true

