---
# Per environment values which override defaults in hmpps-community-payback-api/values.yaml

generic-service:
  ingress:
    host: community-payback-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    SENTRY_ENVIRONMENT: prod
    SPRING_PROFILES_ACTIVE: prod

    COMMUNITY_PAYBACK_DOMAIN_EVENTS_DETAILS_URL_PATTERN: https://community-payback-api.hmpps.service.justice.gov.uk/domain-event-details/#type/#id

    CLIENT_ARNS_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-community-payback-prod
