---
# Per environment values which override defaults in hmpps-community-payback-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: community-payback-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    SENTRY_ENVIRONMENT: preprod
    SPRING_PROFILES_ACTIVE: preprod

    COMMUNITY_PAYBACK_DOMAIN_EVENTS_URLS_APPOINTMENT_UPDATED: https://community-payback-api-preprod.hmpps.service.justice.gov.uk/domain-event-details/appointment-updated

    CLIENT_ARNS_URL: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-community-payback-nonprod
